name: Build Quazal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Specify the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore src/quazal

    - name: Build project
      run: dotnet build src/quazal --configuration Release --no-restore
